import { User } from '../../src/models';

export const seedUsers = async (colleges: any[], attachments: any[]) => {
  console.log('🌱 Seeding users...');
  
  const usersData = [
    {
      firstName: 'John',
      lastName: 'Doe',
      email: 'john.doe@example.com',
      username: 'johndoe',
      status: 'active',
      collegeId: colleges[0]?._id,
      bio: 'Passionate full-stack developer with 3 years of experience in React and Node.js',
      yoe: 3,
      title: 'Senior Frontend Engineer',
      profilePictureAttachmentId: attachments[0]?._id,
      location: 'Mumbai, India',
      visibility: 'public',
      workosId: 'user_workos_1',
      role: 'student',
      userType: 'student_fresher',
      college: colleges[0]?._id,
      year: 3,
      skills: [],
      portfolio: [],
      mentors: [],
      progress: {
        currentGoal: 'Master React and Node.js',
        completionRate: 65
      },
      completionRate: 65,
      isOnboardingComplete: true,
      selectedModules: []
    },
    {
      firstName: 'Jane',
      lastName: 'Smith',
      email: 'jane.smith@example.com',
      username: 'janesmith',
      status: 'active',
      collegeId: colleges[1]?._id,
      bio: 'AI/ML enthusiast and data science student',
      yoe: 2,
      title: 'Data Science Student',
      profilePictureAttachmentId: attachments[1]?._id,
      location: 'Delhi, India',
      visibility: 'public',
      workosId: 'user_workos_2',
      role: 'student',
      userType: 'student_fresher',
      college: colleges[1]?._id,
      year: 4,
      skills: [],
      portfolio: [],
      mentors: [],
      progress: {
        currentGoal: 'Complete Machine Learning course',
        completionRate: 40
      },
      completionRate: 40,
      isOnboardingComplete: true,
      selectedModules: []
    },
    {
      firstName: 'Mike',
      lastName: 'Johnson',
      email: 'mike.johnson@example.com',
      username: 'mikejohnson',
      status: 'active',
      collegeId: colleges[2]?._id,
      bio: 'Backend developer specializing in Java and Spring Boot',
      yoe: 5,
      title: 'Senior Backend Engineer',
      profilePictureAttachmentId: attachments[2]?._id,
      location: 'Chennai, India',
      visibility: 'public',
      workosId: 'user_workos_3',
      role: 'mentor',
      userType: 'working_professional',
      college: colleges[2]?._id,
      year: null,
      skills: [],
      portfolio: [],
      mentors: [],
      progress: {
        currentGoal: 'Mentor students in Java development',
        completionRate: 90
      },
      completionRate: 90,
      isOnboardingComplete: true,
      selectedModules: []
    },
    {
      firstName: 'Sarah',
      lastName: 'Wilson',
      email: 'sarah.wilson@example.com',
      username: 'sarahwilson',
      status: 'active',
      collegeId: colleges[3]?._id,
      bio: 'UI/UX designer and frontend developer',
      yoe: 4,
      title: 'UI/UX Designer',
      profilePictureAttachmentId: attachments[3]?._id,
      location: 'Bangalore, India',
      visibility: 'public',
      workosId: 'user_workos_4',
      role: 'mentor',
      userType: 'working_professional',
      college: colleges[3]?._id,
      year: null,
      skills: [],
      portfolio: [],
      mentors: [],
      progress: {
        currentGoal: 'Help students with design and frontend development',
        completionRate: 85
      },
      completionRate: 85,
      isOnboardingComplete: true,
      selectedModules: []
    },
    {
      firstName: 'David',
      lastName: 'Brown',
      email: 'david.brown@example.com',
      username: 'davidbrown',
      status: 'active',
      collegeId: colleges[4]?._id,
      bio: 'DevOps engineer with expertise in AWS and Docker',
      yoe: 6,
      title: 'DevOps Engineer',
      profilePictureAttachmentId: attachments[4]?._id,
      location: 'Pune, India',
      visibility: 'public',
      workosId: 'user_workos_5',
      role: 'mentor',
      userType: 'working_professional',
      college: colleges[4]?._id,
      year: null,
      skills: [],
      portfolio: [],
      mentors: [],
      progress: {
        currentGoal: 'Teach cloud computing and DevOps practices',
        completionRate: 95
      },
      completionRate: 95,
      isOnboardingComplete: true,
      selectedModules: []
    },
    {
      firstName: 'Emily',
      lastName: 'Davis',
      email: 'emily.davis@example.com',
      username: 'emilydavis',
      status: 'active',
      collegeId: colleges[5]?._id,
      bio: 'Computer science student interested in algorithms and competitive programming',
      yoe: 1,
      title: 'Computer Science Student',
      profilePictureAttachmentId: attachments[5]?._id,
      location: 'Kolkata, India',
      visibility: 'public',
      workosId: 'user_workos_6',
      role: 'student',
      userType: 'student_fresher',
      college: colleges[5]?._id,
      year: 2,
      skills: [],
      portfolio: [],
      mentors: [],
      progress: {
        currentGoal: 'Improve problem-solving skills',
        completionRate: 30
      },
      completionRate: 30,
      isOnboardingComplete: true,
      selectedModules: []
    },
    {
      firstName: 'Alex',
      lastName: 'Garcia',
      email: 'alex.garcia@example.com',
      username: 'alexgarcia',
      status: 'active',
      collegeId: colleges[6]?._id,
      bio: 'Mobile app developer using React Native and Flutter',
      yoe: 3,
      title: 'Mobile App Developer',
      profilePictureAttachmentId: attachments[6]?._id,
      location: 'Hyderabad, India',
      visibility: 'public',
      workosId: 'user_workos_7',
      role: 'student',
      userType: 'student_fresher',
      college: colleges[6]?._id,
      year: 4,
      skills: [],
      portfolio: [],
      mentors: [],
      progress: {
        currentGoal: 'Build cross-platform mobile apps',
        completionRate: 55
      },
      completionRate: 55,
      isOnboardingComplete: true,
      selectedModules: []
    },
    {
      firstName: 'Lisa',
      lastName: 'Anderson',
      email: 'lisa.anderson@example.com',
      username: 'lisaanderson',
      status: 'active',
      collegeId: colleges[7]?._id,
      bio: 'Cybersecurity specialist and ethical hacker',
      yoe: 7,
      title: 'Cybersecurity Specialist',
      profilePictureAttachmentId: attachments[7]?._id,
      location: 'Gurgaon, India',
      visibility: 'public',
      workosId: 'user_workos_8',
      role: 'mentor',
      userType: 'working_professional',
      college: colleges[7]?._id,
      year: null,
      skills: [],
      portfolio: [],
      mentors: [],
      progress: {
        currentGoal: 'Educate students about cybersecurity',
        completionRate: 88
      },
      completionRate: 88,
      isOnboardingComplete: true,
      selectedModules: []
    },
    {
      firstName: 'Ryan',
      lastName: 'Taylor',
      email: 'ryan.taylor@example.com',
      username: 'ryantaylor',
      status: 'active',
      collegeId: colleges[8]?._id,
      bio: 'Blockchain developer and cryptocurrency enthusiast',
      yoe: 4,
      title: 'Blockchain Developer',
      profilePictureAttachmentId: attachments[8]?._id,
      location: 'Ahmedabad, India',
      visibility: 'public',
      workosId: 'user_workos_9',
      role: 'mentor',
      userType: 'working_professional',
      college: colleges[8]?._id,
      year: null,
      skills: [],
      portfolio: [],
      mentors: [],
      progress: {
        currentGoal: 'Teach blockchain development',
        completionRate: 92
      },
      completionRate: 92,
      isOnboardingComplete: true,
      selectedModules: []
    },
    {
      firstName: 'Maya',
      lastName: 'Patel',
      email: 'maya.patel@example.com',
      username: 'mayapatel',
      status: 'active',
      collegeId: colleges[9]?._id,
      bio: 'Full-stack developer with expertise in MERN stack',
      yoe: 2,
      title: 'Full Stack Developer',
      profilePictureAttachmentId: attachments[9]?._id,
      location: 'Jaipur, India',
      visibility: 'public',
      workosId: 'user_workos_10',
      role: 'student',
      userType: 'student_fresher',
      college: colleges[9]?._id,
      year: 3,
      skills: [],
      portfolio: [],
      mentors: [],
      progress: {
        currentGoal: 'Master the complete MERN stack',
        completionRate: 70
      },
      completionRate: 70,
      isOnboardingComplete: true,
      selectedModules: []
    }
  ];

  const users = await User.insertMany(usersData);
  console.log(`✅ Seeded ${users.length} users`);
  
  return users;
};
